<Project>

  <PropertyGroup>
    <Company>collabskus</Company>
    <Authors>kushal</Authors>
    <RepositoryUrl>https://github.com/collabskus/appointme.git</RepositoryUrl>
    <RepositoryType>Git</RepositoryType>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>false</WarningsAsErrors>
    <NoWarn>$(NoWarn);NU1608</NoWarn>
  </PropertyGroup>

</Project>
