global using AppointMe.Shared.Authorization.Principals;
global using AppointMe.Shared.Companies;
global using AppointMe.Shared.Domain;
global using AppointMe.Shared.Domain.Common;
global using AppointMe.Shared.Domain.Errors;
global using AppointMe.Shared.Endpoints;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Routing;
global using Microsoft.EntityFrameworkCore;
global using Wolverine;
global using static AppointMe.Shared.Domain.Id;
